version: '3.8'

services:
  notify-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - APP_PORT=8081
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your-email@gmail.com
      - SMTP_PASS=your-app-password
      - SMTP_FROM=your-email@gmail.com
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_EXCHANGE=email_otp_exchange
      - RABBITMQ_QUEUE=email_otp_queue
      - RABBITMQ_ROUTING_KEY=email.otp.requested
      - RABBITMQ_DLX=email_otp_dlx
      - RABBITMQ_DLQ=email_otp_dlq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
