version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rental-network

  notify-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notify-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - rabbitmq
    networks:
      - rental-network

volumes:
  rabbitmq_data:

networks:
  rental-network:
    driver: bridge